const express = require("express");
const router = express.Router();
const customer = require("../controllers/CustomerController");
router.get("/", customer.getList);
router.get("/details/:id", customer.details);
router.get("/order/:id", customer.orderCustomerId);
router.get("/order/details/:id", customer.orderById);
router.post("/add", customer.add);
router.put("/update/:id",customer.updateById);
router.delete("/delete/:id", customer.deleteById);
module.exports = router;
